import Head from 'next/head';
import Hero from '../components/hero/hero';
import About from '../components/about/about';
import Footer from '../components/footer/footer';
import Headline from '../components/headline/headline';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <About />
      <Headline />
      <Footer />
    </>
  );
}
